services:
  nginx:
    image: nginx:latest
    container_name: nginx-test
    ports:
       - 8001:80
    volumes:
      - ../.docker:/usr/share/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Europe/Paris      

  fpm:
    image: php:8.2-fpm
    container_name: php-fpm-test
    command: php-fpm -R
    ports:
      - 9000:9000
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
      - ../.docker:/usr/share/nginx
    environment:
      - TZ=Europe/Paris

