name: Test and Deploy
run-name: ${{ github.actor }} has triggered Test and Deploy 🚀
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout files in the runner
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: .vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Install prod and dev dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
       
      - name: Generate .env file from .env-example
        run: |
          cp .env-example .env
      
      - name: Run all test suites
        run: composer server & sleep 1 && composer tests-all
        env:
          XDEBUG_MODE: coverage

  deploy:
    needs: test
    runs-on: ubuntu-24.04

    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Setup WARP to enable IPv6
        uses: fscarmen/warp-on-actions@v1.0

      - name: Checkout files in the runner
        uses: actions/checkout@v4

      - name: Set up Python 3.12 for WARP
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install only prod dependencies
        run: composer install --no-dev --prefer-dist --no-progress

      - name: Prepare shipping dir
        run: ./.github/copy-dist.sh

      - name: Deploy to prod on BAAL
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.BAAL_KEYS }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ vars.BAAL_ADDR }}
          REMOTE_USER: ${{ secrets.BAAL_USER }}
          REMOTE_PORT: ${{ secrets.BAAL_PORT }}
          TARGET: ${{ vars.BAAL_PATH }}/${{ github.ref_name }}
          SCRIPT_BEFORE: |
            ls
          SCRIPT_AFTER: |
            ls
            ln -snfr ${{ vars.BAAL_PATH }}/${{ github.ref_name }} ${{ vars.BAAL_PATH }}/current
